# Application 공통 설정 코드(라고 가정)
spring:
  datasource:
    username: root
    password: 1234

    jpa:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true